DoorsOpen/Controllers/BuildingModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DoorsOpen.Data;
using DoorsOpen.Models;
using Microsoft.AspNetCore.Http;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Authorization;

namespace DoorsOpen.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class BuildingModelsController : Controller
    {
        private readonly SiteDbContext _context;
        private readonly IConfiguration _config;

        public BuildingModelsController(SiteDbContext context, IConfiguration configuration)
        {
            _context = context;
            _config = configuration;
        }

        // GET: BuildingModels
        public async Task<IActionResult> Index()
        {
            
            return View(await _context.Buildings.ToListAsync());
        }

        // GET: BuildingModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buildingModel = await _context.Buildings
                .FirstOrDefaultAsync(m => m.Id == id);
            if (buildingModel == null)
            {
                return NotFound();
            }

            return View(new BuildingViewModel(buildingModel, _config.GetValue<string>("AzureImagePrefix")));
        }

        // GET: BuildingModels/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BuildingModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Building,Address1,Address2,City,State,Zip,WheelchairAccessible,RestroomsAvailable,WheelchairAccessibleRestroom,PhotographyAllowed,StartTime,EndTime,Capacity,HistoricalOverview,VisitorExperience,Image")] BuildingModel buildingModel, IFormFile upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null)
                {
                    string imageName = GetFileName(upload);
                    buildingModel.Image = imageName;
                    UploadToAzure(imageName, upload);
                }
                
                _context.Add(buildingModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(buildingModel);
        }

        // GET: BuildingModels/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buildingModel = await _context.Buildings.FindAsync(id);
            if (buildingModel == null)
            {
                return NotFound();
            }
            return View(new BuildingViewModel(buildingModel, _config.GetValue<string>("AzureImagePrefix")));
        }

        // POST: BuildingModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Building,Address1,Address2,City,State,Zip,WheelchairAccessible,RestroomsAvailable,WheelchairAccessibleRestroom,PhotographyAllowed,StartTime,EndTime,Capacity,HistoricalOverview,VisitorExperience,Image")] BuildingModel buildingModel, IFormFile upload)
        {
            if (id != buildingModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var buildingToEdit = await _context.Buildings.Where(b => b.Id == buildingModel.Id).FirstOrDefaultAsync();

                var deleteImage = false;
                if (buildingToEdit.Image != buildingModel.Image || upload != null)
                {
                    if (!string.IsNullOrEmpty(buildingModel.Image))
                    {
                        deleteImage = true;
                    }
                }

                if (deleteImage)
                {
                    if (!string.IsNullOrEmpty(buildingModel.Image))
                    {
                        DeleteFromAzure(buildingModel.Image);
                        buildingModel.Image = null;
                    }
                }

                if (upload != null)
                {
                    string imageName = GetFileName(upload);
                    buildingModel.Image = imageName;
                    UploadToAzure(imageName, upload);
                    Console.WriteLine(buildingModel.Image);
                }

                buildingToEdit.Building = buildingModel.Building;
                buildingToEdit.Address1 = buildingModel.Address1;
                buildingToEdit.Address2 = buildingModel.Address2;
                buildingToEdit.City = buildingModel.City;
                buildingToEdit.State = buildingModel.State;
                buildingToEdit.Zip = buildingModel.Zip;
                buildingToEdit.WheelchairAccessible = buildingModel.WheelchairAccessible;
                buildingToEdit.RestroomsAvailable = buildingModel.RestroomsAvailable;
                buildingToEdit.WheelchairAccessibleRestroom = buildingModel.WheelchairAccessibleRestroom;
                buildingToEdit.PhotographyAllowed = buildingModel.PhotographyAllowed;
                buildingToEdit.StartTime = buildingModel.StartTime;
                buildingToEdit.EndTime = buildingModel.EndTime;
                buildingToEdit.Capacity = buildingModel.Capacity;
                buildingToEdit.HistoricalOverview = buildingModel.HistoricalOverview;
                buildingToEdit.VisitorExperience = buildingModel.VisitorExperience;
                buildingToEdit.Image = buildingModel.Image;

                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(buildingModel);
        }

        // GET: BuildingModels/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buildingModel = await _context.Buildings
                .FirstOrDefaultAsync(m => m.Id == id);
            if (buildingModel == null)
            {
                return NotFound();
            }

            return View(buildingModel);
        }

        // POST: BuildingModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var buildingModel = await _context.Buildings.FindAsync(id);
            _context.Buildings.Remove(buildingModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BuildingModelExists(int id)
        {
            return _context.Buildings.Any(e => e.Id == id);
        }

        public string GetFileName(IFormFile upload)
        {
            int indexExt = 0;
            string ext;
            string imageName = null;
            if (upload != null)
            {
                indexExt = upload.FileName.IndexOf(".");
                ext = upload.FileName.Substring(indexExt);
                imageName = Guid.NewGuid() + ext;
            }
            return imageName;
        }

        public void UploadToAzure(string imageName, IFormFile upload)
        {
            // Azure needs your connection string like a db
            string connectionString = Environment.GetEnvironmentVariable("AZURE_STORAGE_CONNECTION_STRING");
            if (string.IsNullOrEmpty(connectionString))
            {
                connectionString = _config.GetValue<string>("AzureConnectionString");
            }
            BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);
            // Azure needs to know what folder you want to save in
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(_config.GetValue<string>("AzureImageFolder"));
            // Then, you can get a blob writer thing from azure
            containerClient.UploadBlob(imageName, upload.OpenReadStream());
        }

        public void DeleteFromAzure(string imageName)
        {
            // need connection to Azure just like a local db
            string connectionString = Environment.GetEnvironmentVariable("AZURE_STORAGE_CONNECTION_STRING");
            if (string.IsNullOrEmpty(connectionString))
            {
                connectionString = _config.GetValue<string>("AzureConnectionString");
            }
            // connect to Azure
            BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);
            // go to a specific folder
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(_config.GetValue<string>("AzureImageFolder"));
            // find a specific file
            BlobClient blob = containerClient.GetBlobClient($"{imageName}");        
            // delete if exists
            if (blob.Exists())
            {
                blob.Delete();
            }
        }
    }
}

DoorsOpen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DOORSOPENPGH</title>
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="~/assets/css/now-ui-dashboard.css"> <!-- Copied in from ui dashboard-->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="">
    <div class="wrapper">
        <div class="sidebar" data-color="orange">
            <div class="logo">
                <a href="https://doorsopenpgh.org/" class="simple-text logo-mini" target ="_blank">
                    <i class="now-ui-icons shopping_shop"></i>
                </a>

                <a href="https://doorsopenpgh.org/" class="simple-text logo-normal" target ="_blank">
                    Doors Open PGH
                </a>

            </div>

            <div class="sidebar-wrapper">

                <ul class="nav">

                    <li>
                        <a data-toggle="collapse" href="#pagesBuildings">
                            <i class="now-ui-icons business_bank"></i>
                            <p>
                                Buildings
                                <b class="caret"></b>
                            </p>
                        </a>



                        <div class="collapse" id="pagesBuildings">
                            <ul class="nav">
                                <li>
                                    <a asp-controller="BuildingModels" asp-action="Index">
                                        <span class="sidebar-mini-icon">V</span>
                                        <span class="sidebar-normal">View All</span>
                                    </a>
                                </li>
                                <li>
                                    <a asp-controller="BuildingModels" asp-action="Create">
                                        <span class="sidebar-mini-icon">+</span>
                                        <span class="sidebar-normal">Create</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>

                    <li>
                        <a data-toggle="collapse" href="#pagesEvents">
                            <i class="now-ui-icons ui-1_email-85"></i>
                            <p>
                                Events
                                <b class="caret"></b>
                            </p>
                        </a>

                        <div class="collapse" id="pagesEvents">
                            <ul class="nav">
                                <li class="pleasework">
                                    <a href="/EventModels/Index">
                                        <span class="sidebar-mini-icon">V</span>
                                        <span class="sidebar-normal">View All</span>
                                    </a>
                                </li>
                                <li class="pleasework">
                                    <a href="/EventModels/Create">
                                        <span class="sidebar-mini-icon">+</span>
                                        <span class="sidebar-normal">Create</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

        <div class="main-panel">
            <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute">
                <div class="container-fluid">


                    <div class="navbar-wrapper">
                        <div class="navbar-toggle">
                            <button type="button" class="navbar-toggler">
                                <span class="navbar-toggler-bar bar1"></span>
                                <span class="navbar-toggler-bar bar2"></span>
                                <span class="navbar-toggler-bar bar3"></span>
                            </button>
                        </div>
                        <a class="navbar-brand" href="#pablo">Dashboard</a>
                    </div>

                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                    </div>
                    
                </div>
            </nav>

            <div class="my-panel-header">
            </div>

            <div class="content">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <!-- All script info below is copied in from ui dashboard-->
    <script src="/assets/js/plugins/perfect-scrollbar.jquery.min.js" type="text/javascript"></script>
    <script src="/assets/js/plugins/moment.min.js"></script>

    <!--  Plugin for Sweet Alert -->
    <script src="/assets/js/plugins/sweetalert2.min.js"></script>

    <!-- Forms Validations Plugin -->
    <script src="/assets/js/plugins/jquery.validate.min.js"></script>

    <!--  Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
    <script src="/assets/js/plugins/jquery.bootstrap-wizard.js"></script>

    <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
    <script src="/assets/js/plugins/bootstrap-selectpicker.js" type="text/javascript"></script>

    <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
    <script src="/assets/js/plugins/bootstrap-switch.js"></script>

    <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
    <script src="/assets/js/plugins/bootstrap-datetimepicker.js"></script>

    <!--  DataTables.net Plugin, full documentation here: https://datatables.net/    -->
    <script src="/assets/js/plugins/jquery.dataTables.min.js"></script>

    <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
    <script src="/assets/js/plugins/bootstrap-tagsinput.js"></script>

    <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
    <script src="/assets/js/plugins/jasny-bootstrap.min.js"></script>

    <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
    <script src="/assets/js/plugins/fullcalendar.min.js"></script>

    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src="/assets/js/plugins/nouislider.min.js" type="text/javascript"></script>

    <!-- Chart JS -->
    <script src="/assets/js/plugins/chartjs.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="/assets/js/plugins/bootstrap-notify.js"></script>

    <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->

    <script src="/assets/js/now-ui-dashboard.js" type="text/javascript"></script>



</body>
</html>